# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "/pdf/*.pdf"
  - "/.vscode/*.settings.json"

# Any typos we should ignore?
excluded_words:
  - AMD
  - Allostream
  - Animés
  - Annuaire
  - Annuaire-telechargement-fr
  - CHEF-KOCH
  - CODEX
  - Cloudflare
  - CompucaliTV
  - Comédie
  - Demoscene
  - Discord
  - Filesharing
  - Filmcomplet
  - Filmz
  - GDrive
  - GIndex
  - Genration
  - GoIndex
  - Good-Old-Downloads
  - Google
  - Google Cloud
  - Gratuit
  - Horreur
  - IGG
  - Intel
  - IzzyonDroid
  - Kabel-Receiver
  - Kkiste
  - Matrix
  - Megadede
  - Microsoft
  - Mobdro
  - Movidy
  - MultCloud
  - NZB
  - Netflix
  - Nsane
  - Offline
  - PCMYMJuegos
  - Papystreaming
  - Public
  - RClone
  - Razor
  - Reddit
  - Regarder
  - Riot
  - Rosco
  - Serie-Streaming
  - Sokrostream
  - SpaceX
  - Spotify
  - Steam
  - SteamWorkFixs
  - Streamcomplet
  - SzeneBox
  - Série
  - Toorgle
  - Trackers
  - Tutorialspoint
  - Warez
  - Warez-Scene
  - WawaCity
  - Wget
  - Wikipedia
  - Wikiserie
  - XpoMusic
  - ZippyShare
  - actions-makepdfs
  - alamy
  - autres
  - complets
  - cybermania
  - des
  - devbots
  - différents
  - downeu
  - dpstream
  - file-sharing
  - française
  - gDrive
  - gratuit
  - gratuit
  - gsettings
  - herbergeurs
  - hoster
  - kkiboeco
  - les
  - makepdfs
  - mangas
  - meme
  - mkrakowitzer
  - mkvcagez
  - monkrus
  - nVidia
  - rClone
  - remuxes
  - repacker
  - spyoungtech
  - szb
  - sélections
  - séries
  - torrenting
  - typoci
  - téléchargement
  - voir
  - votre
  - yasdl


# Would you like filenames to also be spellchecked?
spellcheck_filenames: no
